/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.loja.ui.principal;

import br.com.loja.ui.categoria.CadastroCategoria;
import br.com.loja.ui.cliente.CadastroCliente;
import br.com.loja.ui.produto.CadastroProduto;
import br.com.loja.ui.venda.EfetuarVenda;
import javax.swing.JFrame;

/**
 *
 * @author yuri
 */
public class TelaPrincipal extends javax.swing.JFrame {
    private CadastroCliente telaCliente = null;
    private CadastroProduto telaProduto = null;
    private CadastroCategoria telaCategoria = null;
    private EfetuarVenda efetuarvenda = null;
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        user = new javax.swing.JMenu();
        createUser = new javax.swing.JMenuItem();
        searchUser = new javax.swing.JMenuItem();
        product = new javax.swing.JMenu();
        createProduct = new javax.swing.JMenuItem();
        venda = new javax.swing.JMenu();
        vendaItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        user.setText("Cliente");

        createUser.setText("Cadastrar Cliente");
        createUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createUserActionPerformed(evt);
            }
        });
        user.add(createUser);

        searchUser.setText("Consultar Cliente");
        user.add(searchUser);

        jMenuBar1.add(user);

        product.setText("Produto");

        createProduct.setText("Cadastrar Produto");
        createProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createProductActionPerformed(evt);
            }
        });
        product.add(createProduct);

        jMenuBar1.add(product);

        venda.setText("Venda");

        vendaItem.setText("Efetuar Venda");
        vendaItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendaItemActionPerformed(evt);
            }
        });
        venda.add(vendaItem);

        jMenuBar1.add(venda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 519, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createUserActionPerformed
        // TODO add your handling code here:
        if(telaCliente == null || !telaCliente.isDisplayable()) {
            telaCliente = new CadastroCliente();
            telaCliente.pack();
            telaCliente.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            telaCliente.setLocationRelativeTo(null);
            telaCliente.setVisible(true);
        }
        telaCliente.toFront();
    }//GEN-LAST:event_createUserActionPerformed

    private void createProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createProductActionPerformed
        if(telaProduto == null || !telaCategoria.isDisplayable()) {
            telaProduto = new CadastroProduto();
            telaProduto.pack();
            telaProduto.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            telaProduto.setLocationRelativeTo(null);
            telaProduto.setVisible(true);
        }
        telaProduto.toFront();
    }//GEN-LAST:event_createProductActionPerformed

    private void vendaItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendaItemActionPerformed
        if(efetuarvenda == null || !efetuarvenda.isDisplayable()) {
            efetuarvenda = new EfetuarVenda();
            efetuarvenda.pack();
            efetuarvenda.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            efetuarvenda.setLocationRelativeTo(null);
            efetuarvenda.setVisible(true);
        }
        efetuarvenda.toFront();
    }//GEN-LAST:event_vendaItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem createProduct;
    private javax.swing.JMenuItem createUser;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu product;
    private javax.swing.JMenuItem searchUser;
    private javax.swing.JMenu user;
    private javax.swing.JMenu venda;
    private javax.swing.JMenuItem vendaItem;
    // End of variables declaration//GEN-END:variables
}
